name: osm_flutter
on: [ push, pull_request ]

jobs:
  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image:  python:3
      #image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: setup flutter
        uses: britannio/action-install-flutter@v1
      - run: flutter --version
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
            "expiration": 1583530852703
          }
          EOF
      - name: preparation release
        run: python check_pubspec_release.py
      - name: clear before release
        run: |
          rm -f *.gif
          rm -rf assets
          rm -rf flutter_osm_interface
          rm -rf flutter_osm_web
          rm -f check_pubspec_release.py
      - name: fomarting files
        run : flutter format .
      - name: Publish package
        run:  flutter pub publish -f